


const Logo = ({ teamName }) => {

//     const teamLogos = {
//     "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
//     "Aston Villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
//     "Bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
//     "Brentford": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
//     "Brighton": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
//     "Burnley": "https://a.espncdn.com/i/teamlogos/soccer/500/377.png",
//     "Chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
//     "Crystal Palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
//     "Everton": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
//     "Fulham": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
//     "Leeds": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
//     "Leicester": "https://a.espncdn.com/i/teamlogos/soccer/500/375.png",
//     "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
//     "Man City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
//     "Man United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
//     "Newcastle": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
//     "Nott'm Forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
//     "Sheffield Utd": "https://a.espncdn.com/i/teamlogos/soccer/500/350.png",
//     "Southampton": "https://a.espncdn.com/i/teamlogos/soccer/500/376.png",
//     "Tottenham": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
//     "West Ham": "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
//     "Wolves": "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
//     "Sunderland": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
//     "Alaves": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
//     "Ath Bilbao": "https://a.espncdn.com/i/teamlogos/soccer/500/81.png",
//     "Ath Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
//     "Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
//     "Betis": "https://a.espncdn.com/i/teamlogos/soccer/500/90.png",
//     "Celta": "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
//     "Elche": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
//     "Espanol": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
//     "Getafe": "https://a.espncdn.com/i/teamlogos/soccer/500/95.png",
//     "Girona": "https://a.espncdn.com/i/teamlogos/soccer/500/3807.png",
//     "Granada": "https://a.espncdn.com/i/teamlogos/soccer/500/3747.png",
//     "Levante": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
//     "Mallorca": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
//     "Osasuna": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
//     "Vallecano": "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
//     "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
//     "Sociedad": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
//     "Sevilla": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
//     "Valencia": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
//     "Villarreal": "https://a.espncdn.com/i/teamlogos/soccer/500/99.png",
//     "Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
//     "Roma": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
//     "Atalanta": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
//     "Bologna": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
//     "Cagliari": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
//     "Empoli": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
//     "Fiorentina": "https://a.espncdn.com/i/teamlogos/soccer/500/108.png",
//     "Genoa": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
//     "Verona": "https://a.espncdn.com/i/teamlogos/soccer/500/117.png",
//     "Inter": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
//     "Juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
//     "Lazio": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
//     "Lecce": "https://a.espncdn.com/i/teamlogos/soccer/500/3749.png",
//     "Monza": "https://a.espncdn.com/i/teamlogos/soccer/500/6990.png",
//     "Napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/116.png",
//     "Parma": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
//     "Pisa": "https://a.espncdn.com/i/teamlogos/soccer/500/6982.png",
//     "Salernitana": "https://a.espncdn.com/i/teamlogos/soccer/500/6985.png",
//     "Sassuolo": "https://a.espncdn.com/i/teamlogos/soccer/500/6986.png",
//     "Torino": "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
//     "Udinese": "https://a.espncdn.com/i/teamlogos/soccer/500/120.png",
//     "Como": "https://a.espncdn.com/i/teamlogos/soccer/500/6994.png",
//     "Cremonese": "https://a.espncdn.com/i/teamlogos/soccer/500/6993.png",
//     "Augsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/130.png",
//     "Bayern Munich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
//     "Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
//     "Ein Frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
//     "Freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
//     "Hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/128.png",
//     "Leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
//     "M'gladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
//     "RB Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/7313.png",
//     "Union Berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/141.png",
//     "Wolfsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/136.png",
//     "Mainz": "https://a.espncdn.com/i/teamlogos/soccer/500/135.png",
//     "FC Koln": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
//     "Stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
//     "Werder Bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
//     "Heidenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/7001.png",
//     "Hamburg": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
//     "St Pauli": "https://a.espncdn.com/i/teamlogos/soccer/500/139.png",
//     "Angers": "https://a.espncdn.com/i/teamlogos/soccer/500/157.png",
//     "Auxerre": "https://a.espncdn.com/i/teamlogos/soccer/500/158.png",
//     "Brest": "https://a.espncdn.com/i/teamlogos/soccer/500/173.png",
//     "Clermont": "https://a.espncdn.com/i/teamlogos/soccer/500/385.png",
//     "Lille": "https://a.espncdn.com/i/teamlogos/soccer/500/162.png",
//     "Lens": "https://a.espncdn.com/i/teamlogos/soccer/500/161.png",
//     "Lorient": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
//     "Lyon": "https://a.espncdn.com/i/teamlogos/soccer/500/163.png",
//     "Marseille": "https://a.espncdn.com/i/teamlogos/soccer/500/164.png",
//     "Metz": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
//     "Monaco": "https://a.espncdn.com/i/teamlogos/soccer/500/165.png",
//     "Montpellier": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
//     "Nantes": "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
//     "Nice": "https://a.espncdn.com/i/teamlogos/soccer/500/168.png",
//     "Paris SG": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
//     "Reims": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
//     "Rennes": "https://a.espncdn.com/i/teamlogos/soccer/500/170.png",
//     "Strasbourg": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
//     "Toulouse": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
//     "Le Havre": "https://a.espncdn.com/i/teamlogos/soccer/500/171.png",
//     "Paris FC": "https://a.espncdn.com/i/teamlogos/soccer/500/1916.png",
// };
const teamLogos = {
    "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
    "Aston Villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
    "Bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
    "Brentford": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
    "Brighton": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
    "Burnley": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Burnley_F.C._logo.svg/1200px-Burnley_F.C._logo.svg.png",
    "Chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
    "Crystal Palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
    "Everton": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
    "Fulham": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
    "Leeds": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
    "Leicester": "https://a.espncdn.com/i/teamlogos/soccer/500/375.png",
    "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
    "Man City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
    "Man United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
    "Newcastle": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
    "Nott'm Forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
    "Sheffield Utd": "https://a.espncdn.com/i/teamlogos/soccer/500/350.png",
    "Southampton": "https://a.espncdn.com/i/teamlogos/soccer/500/376.png",
    "Tottenham": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
    "West Ham": "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
    "Wolves": "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
    "Sunderland": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
    "Alaves": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
    "Ath Bilbao": "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Athletic_Bilbao_logo.svg/1200px-Athletic_Bilbao_logo.svg.png",
    "Ath Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
    "Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
    "Betis": "https://a.espncdn.com/i/teamlogos/soccer/500/90.png",
    "Celta": "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
    "Elche": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
    "Espanol": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
    "Getafe": "https://a.espncdn.com/i/teamlogos/soccer/500/95.png",
    "Girona": "https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Girona_FC_logo.svg/1200px-Girona_FC_logo.svg.png",
    "Granada": "https://a.espncdn.com/i/teamlogos/soccer/500/3747.png",
    "Levante": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
    "Mallorca": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
    "Osasuna": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
    "Vallecano": "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
    "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
    "Sociedad": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
    "Sevilla": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
    "Valencia": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
    "Villarreal": "https://a.espncdn.com/i/teamlogos/soccer/500/99.png",
    "Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
    "Roma": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
    "Atalanta": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
    "Bologna": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
    "Cagliari": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
    "Empoli": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
    "Fiorentina": "https://a.espncdn.com/i/teamlogos/soccer/500/108.png",
    "Genoa": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
    "Verona": "https://a.espncdn.com/i/teamlogos/soccer/500/117.png",
    "Inter": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
    "Juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
    "Lazio": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
    "Lecce": "https://upload.wikimedia.org/wikipedia/en/thumb/8/85/U.S._Lecce_logo.svg/1200px-U.S._Lecce_logo.svg.png",
    "Monza": "https://a.espncdn.com/i/teamlogos/soccer/500/6990.png",
    "Napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/116.png",
    "Parma": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
    "Pisa": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f0/Pisa_S.C._logo.svg/1200px-Pisa_S.C._logo.svg.png",
    "Salernitana": "https://a.espncdn.com/i/teamlogos/soccer/500/6985.png",
    "Sassuolo": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/US_Sassuolo_Calcio_logo.svg/1200px-US_Sassuolo_Calcio_logo.svg.png",
    "Torino": "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
    "Udinese": "https://a.espncdn.com/i/teamlogos/soccer/500/120.png",
    "Como": "https://a.espncdn.com/i/teamlogos/soccer/500/6994.png",
    "Cremonese": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/U.S._Cremonese_logo.svg/1200px-U.S._Cremonese_logo.svg.png",
    "Augsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/130.png",
    "Bayern Munich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
    "Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
    "Ein Frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
    "Freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
    "Hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/128.png",
    "Leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
    "M'gladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/129.png",
    "RB Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/7313.png",
    "Union Berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/141.png",
    "Wolfsburg": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/VfL_Wolfsburg_2017_logo.svg/1200px-VfL_Wolfsburg_2017_logo.svg.png",
    "Mainz": "https://a.espncdn.com/i/teamlogos/soccer/500/135.png",
    "FC Koln": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
    "Stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
    "Werder Bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
    "Heidenheim": "https://upload.wikimedia.org/wikipedia/en/thumb/8/84/1._FC_Heidenheim_1846_logo.svg/1200px-1._FC_Heidenheim_1846_logo.svg.png",
    "Hamburg": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
    "St Pauli": "https://a.espncdn.com/i/teamlogos/soccer/500/139.png",
    "Angers": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Angers_SCO_logo.svg/1200px-Angers_SCO_logo.svg.png",
    "Auxerre": "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/A.J._Auxerre_logo.svg/1200px-A.J._Auxerre_logo.svg.png",
    "Brest": "https://a.espncdn.com/i/teamlogos/soccer/500/173.png",
    "Clermont": "https://a.espncdn.com/i/teamlogos/soccer/500/385.png",
    "Lille": "https://a.espncdn.com/i/teamlogos/soccer/500/162.png",
    "Lens": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/RC_Lens_logo.svg/1200px-RC_Lens_logo.svg.png",
    "Lorient": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
    "Lyon": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Olympique_Lyonnais.svg/1200px-Olympique_Lyonnais.svg.png",
    "Marseille": "https://a.espncdn.com/i/teamlogos/soccer/500/164.png",
    "Metz": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
    "Monaco": "https://a.espncdn.com/i/teamlogos/soccer/500/165.png",
    "Montpellier": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
    "Nantes": "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
    "Nice": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/OGC_Nice_logo.svg/1200px-OGC_Nice_logo.svg.png",
    "Paris SG": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
    "Reims": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
    "Rennes": "https://a.espncdn.com/i/teamlogos/soccer/500/170.png",
    "Strasbourg": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
    "Toulouse": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
    "Le Havre": "https://a.espncdn.com/i/teamlogos/soccer/500/171.png",
    "Paris FC": "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Paris_FC_logo.svg/1200px-Paris_FC_logo.svg.png",
    "Real Oviedo": "https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Real_Oviedo_logo.svg/1200px-Real_Oviedo_logo.svg.png"
};
  return (<img
    src={teamLogos[teamName]}
    alt={`${teamName} logo`}
    className='w-6 h-6 mr-2'
    onError={(e) => {
      e.target.onerror = null
      e.target.src =
        'https://a.espncdn.com/i/teamlogos/soccer/500/default-team-logo-500.png'
    }}
  />
)
}
export default Logo
