
 
TEAM_NAME_MAP = {
    "Arsenal": "Arsenal",
    "Aston Villa": "Aston Villa",
    "Bournemouth": "Bournemouth",
    "Brentford": "Brentford",
    "Brighton and Hove Albion": "Brighton",
    "Burnley": "Burnley",
    "Chelsea": "Chelsea",
    "Crystal Palace": "Crystal Palace",
    "Everton": "Everton",
    "Fulham": "Fulham",
    "Leeds United": "Leeds",
    "Leicester City": "Leicester",
    "Liverpool": "Liverpool",
    "Manchester City": "Man City",
    "Manchester United": "Man United",
    "Newcastle United": "Newcastle",
    "Nottingham Forest": "Nott'm Forest",
    "Sheffield United": "Sheffield Utd",
    "Southampton": "Southampton",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
    "Sunderland": "Sunderland",
    "Alavés": "Alaves",
    "Athletic Bilbao": "Ath Bilbao",
    "Atlético Madrid": "Ath Madrid",
    "Barcelona": "Barcelona",
    "Real Betis": "Betis",
    "Celta Vigo": "Celta",
    "Elche CF": "Elche",
    "Espanyol": "Espanol",
    "Getafe": "Getafe",
    "Girona": "Girona",
    "Granada": "Granada",
    "Levante": "Levante",
    "Mallorca": "Mallorca",
    "CA Osasuna": "Osasuna",
    "Rayo Vallecano": "Vallecano",
    "Real Madrid": "Real Madrid",
    "Real Sociedad": "Sociedad",
    "Sevilla": "Sevilla",
    "Valencia": "Valencia",
    "Villarreal": "Villarreal",
    "AC Milan": "Milan",
    "AS Roma": "Roma",
    "Atalanta BC": "Atalanta",
    "Bologna": "Bologna",
    "Cagliari": "Cagliari",
    "Empoli": "Empoli",
    "Fiorentina": "Fiorentina",
    "Genoa": "Genoa",
    "Hellas Verona": "Verona",
    "Inter Milan": "Inter",
    "Juventus": "Juventus",
    "Lazio": "Lazio",
    "Lecce": "Lecce",
    "Monza": "Monza",
    "Napoli": "Napoli",
    "Parma": "Parma",
    "Pisa": "Pisa",
    "Salernitana": "Salernitana",
    "Sassuolo": "Sassuolo",
    "Torino": "Torino",
    "Udinese": "Udinese",
    "Como": "Como",
    "Cremonese": "Cremonese",
    "Augsburg": "Augsburg",
    "Bayern Munich": "Bayern Munich",
    "Borussia Dortmund": "Dortmund",
    "Eintracht Frankfurt": "Ein Frankfurt",
    "SC Freiburg": "Freiburg",
    "TSG Hoffenheim": "Hoffenheim",
    "Bayer Leverkusen": "Leverkusen",
    "Borussia Monchengladbach": "M'gladbach",
    "RB Leipzig": "RB Leipzig",
    "Union Berlin": "Union Berlin",
    "VfL Wolfsburg": "Wolfsburg",
    "FSV Mainz 05": "Mainz",
    "1. FC Köln": "FC Koln",
    "VfB Stuttgart": "Stuttgart",
    "Werder Bremen": "Werder Bremen",
    "1. FC Heidenheim": "Heidenheim",
    "Hamburger SV": "Hamburg",
    "FC St. Pauli": "St Pauli",
    "Angers": "Angers",
    "Auxerre": "Auxerre",
    "Brest": "Brest",
    "Clermont": "Clermont",
    "Lille": "Lille",
    "RC Lens": "Lens",
    "Lorient": "Lorient",
    "Olympique Lyonnais": "Lyon",
    "Olympique de Marseille": "Marseille",
    "Metz": "Metz",
    "AS Monaco": "Monaco",
    "Montpellier": "Montpellier",
    "Nantes": "Nantes",
    "Nice": "Nice",
    "Paris Saint Germain": "Paris SG",
    "Reims": "Reims",
    "Rennes": "Rennes",
    "Strasbourg": "Strasbourg",
    "Toulouse": "Toulouse",
    "Le Havre": "Le Havre",
    "Paris FC": "Paris FC"
}


def normalize_team_name(api_name):
    return TEAM_NAME_MAP.get(api_name, api_name)

