export const TEAMS = [
  // Premier League
  'Arsenal',
  'Aston Villa',
  'Bournemouth',
  'Brentford',
  'Brighton',
  'Chelsea',
  'Crystal Palace',
  'Everton',
  'Fulham',
  'Liverpool',
  'Luton',
  'Man City',
  'Man United',
  'Newcastle',
  'Nottingham Forest',
  'Sheffield United',
  'Tottenham',
  'West Ham',
  'Wolves',
  'Burnley',
  'Sunderland',
  'Leeds',
  // La Liga
  'Alaves',
  'Almeria',
  'Athletic Club',
  'Atletico Madrid',
  'Barcelona',
  'Cadiz',
  'Celta Vigo',
  'Getafe',
  'Girona',
  'Granada',
  'Las Palmas',
  'Mallorca',
  'Osasuna',
  'Rayo Vallecano',
  'Real Betis',
  'Real Madrid',
  'Real Sociedad',
  'Sevilla',
  'Valencia',
  'Villarreal',
  // Serie A
  'AC Milan',
  'Atalanta',
  'Bologna',
  'Cagliari',
  'Empoli',
  'Fiorentina',
  'Frosinone',
  'Genoa',
  'Inter',
  'Juventus',
  'Lazio',
  'Lecce',
  'Monza',
  'Napoli',
  'Roma',
  'Salernitana',
  'Sassuolo',
  'Torino',
  'Udinese',
  'Verona',
  // Bundesliga
  'Augsburg',
  'Bayer Leverkusen',
  'Bayern Munich',
  'Bochum',
  'Darmstadt',
  'Dortmund',
  'Eintracht Frankfurt',
  'FC Heidenheim',
  'FC Koln',
  'Freiburg',
  'Hoffenheim',
  'Mainz 05',
  'Monchengladbach',
  'RB Leipzig',
  'Stuttgart',
  'Union Berlin',
  'Werder Bremen',
  'Wolfsburg',
  // Ligue 1
  'Brest',
  'Clermont Foot',
  'Le Havre',
  'Lens',
  'Lille',
  'Lorient',
  'Lyon',
  'Marseille',
  'Metz',
  'Monaco',
  'Montpellier',
  'Nantes',
  'Nice',
  'Paris SG',
  'Reims',
  'Rennes',
  'Strasbourg',
  'Toulouse',
].sort()
